---
- name: template project files
  template:
    src: '{{ item }}'
    dest: /tmp/{{ item[0:-3] }}
  with_items:
    - etcd-statefulset.yaml.j2
    - postgresql-ha-stateful.yaml.j2
  register: templates

- name: OpenShift Use Project
  command: "oc project {{ project_name }}"
  ignore_errors: True
  register: use_project

- name: OpenShift Create Project
  command: "oc new-project {{ project_name }}"
  when: use_project | failed

- name: OpenShift Create Resources
  command: "oc create -f {{ item.dest }}"
  with_items: "{{ templates.results }}"
  when: item | changed
