---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations: {}
    labels: {}
    name: postgres 
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: postgres_edit 
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: postgres 
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    name: psql-ha-poc
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    - name: 8008-tcp
      port: 8008
      protocol: TCP
      targetPort: 8008
    selector:
      app: psql-ha-poc
      deploymentconfig: psql-ha-poc
      role: master
    sessionAffinity: None
    type: ClusterIP
